Mission editorial refactor
w3c/AB-public pull request #162
Opened 2024-03-27 20:22 UTC by cwilso

This PR fixes #161 ; it keeps all content text, but moves the brief elevator pitch to the beginning of the Vision for W3C section, and moves one paragraph from there to the introduction (putting all the "history" together in one place, more clearly identifying what is looking forward and what is looking back).

2024-03-27 23:54 UTC, tantek approved these changes
GitHub messes up the diff, however I went through it line-by-line and verified this is a content move, without edits of the content inside, and dropping of the "The Mission" heading (for now). 

This is a good tightening up for the Note, given that we've captured the remaining "Mission" work in #163 which we can work on and iterate after publishing the Note.

2024-03-28 09:38 UTC, koalie requested changes
I approve the changes per se.
In looking at the diff/preview I noted three instances of "(t|T)he W3C" where "W3C" isn't used as an adjective. I don't know how to made those edits myself.
Please remove "(t|T)he" 🙏 
cf. https://www.w3.org/about/press-media/#w3c-brand

2024-03-28 12:56 UTC, amyvdh commented
I very much approve the adjustments as noted. The statements are clear and grounded.

2024-03-28 14:58 UTC, cwilso commented
@koalie I filed https://github.com/w3c/AB-public/issues/164 to resolve the branding guidelines, and will do that next.  (Since it's not introduced with this PR, I wanted to keep it separate.)

2024-03-28 14:58 UTC, merged