Split diverse perspectives and inclusion points
w3c/AB-public pull request #171
Opened 2024-04-12 02:13 UTC by cwilso

An attempt to address #169:  split out diversity and inclusion to address separately.  There is clear overlap, of course, which is why both lists are open-ended.

2024-04-12 04:43 UTC, wareid approved these changes

2024-04-12 05:40 UTC, chrisn approved these changes

2024-04-12 07:36 UTC, chaals approved these changes
thanks @cwilso - I think this is an excellent change that addresses the issue raised very well, as well as my initial skepticism regarding aa proposed solution.

2024-04-13 05:47 UTC, tantek approved these changes
This is an improvement. 

I'm not sure about the final line "This ensures W3C serves the needs of the entire Web user base." — it seems like an aspirational conclusion rather than stating what we will do (like the previous section's "we will actively seek to be inclusive to all."). 

We can iterate on that though.

2024-04-15 15:49 UTC, fantasai requested changes
By shifting languages and cultures to diversity of participation and out of diversity of perspective, I think this edit loses that we need people from different cultures, languages, etc. in order to make sure that W3C serves the needs of the entire Web user base. That's a significant regression.

More generally, but by splitting the two lists we have a problem: diversity of perspective is not limited to things _other_ than personal characteristics; and inclusion needs to _also_ accommodate things like geographic locales and organizational sizes, not just personal characteristics.

To give a few concrete examples:
- We need people from different languages to ensure that the Web can render all of those languages correctly, not just to be inclusive as an organization.
- We make efforts to welcome effective participation from small companies with limited resources (not just those at Google/Apple scale), not just because we want their perspective on our work, but because we want W3C to be inclusive across more of society.
- We need people from different cultures not just to help our organization to be diverse and welcoming, but to ensure that the Web platform can serve the use cases of different cultures.
- We are struggling with inclusion wrt participants from China not just because of their culture or language, but because they are _physically located in China_, and that creates problems wrt time zones and access to the information so many W3C participants casually store in Google documents.

I think it's good to make a point about inclusion and providing a welcoming environment, but splitting hairs about what qualifies as a legitimate axis of diversity in one category or another doesn't seem to be helping.

2024-04-15 16:50 UTC, cwilso commented
This absolutely is not intended to hairsplit about what is a legitimate axis of diverse opinion vs inclusion; that's precisely why both lists are open-ended ("...and more").  The explicit ask was to split diverse perspectives out from inclusion; yes, some things can certainly be factors in both.  Short of having things like language occur in both lists, I don't think this is resolvable, which is why I went with a brief, succinct, and open-ended approach.

2024-04-16 05:25 UTC, fantasai commented
Both lists are open-ended, but there's no overlap, not even on ones that are particularly relevant to W3C. It supports the argument (that has been made) that some of these are not valid considerations in one list or the other.

2024-10-02 21:42 UTC, tantek requested changes
Given the lack of consensus in the discussion on this PR, and that no one has raised this as a Statement-blocker (or even a next-note-blocker) either explicitly or implicitly in the comments, I'd like to defer this PR until after we publish an updated NOTE and go for wide review, and solicit wide review comments on the respective issue to see if that demonstrates a strong focus of potential consensus.

2024-11-28 05:09 UTC, JonnyBnice84 approved these changes

2025-01-14 06:35 UTC, cwilso commented
(this PR will not be merged)

2025-01-14 06:35 UTC, closed without merging