[Vision] Add technical soundness and architectural integrity to Thorough Review
w3c/AB-public pull request #173
Opened 2024-09-25 22:06 UTC by fantasai

Addresses #170 #141

2024-09-25 22:32 UTC, cwilso commented
I would rather view this as #170 fixes #141, and only mention "technical soundness".

2024-09-25 23:42 UTC, fantasai commented
@cwilso I'm not sure I understand your comment, but I think these are two different (certainly related) things:
- technical soundness is something we ensure through the deep review that happens through our WG discussions, and through our implementation experience requirements -- ensuring out specs are thorough, detailed, well-thought out
- architectural integrity is about ensuring the whole system hangs together, and we do it mainly through TAG review and that kind of thing

We do both, and both are valuable, but they are distinct; so that's why I kept them distinct in the PR.

2024-09-25 23:56 UTC, tantek approved these changes
Upon deeper reflection and a bit of research of prior wording of these things at W3C (multiple sources), I have edited the PR to a single line to encapsulate both in a shorter phrase that has established use at W3C.

I do agree with the use-cases / motivations in both issues @fantasai has mentioned and believe this edit now reinforces and resolves both.

2024-09-26 16:18 UTC, fantasai commented
@tantek I don't think that encompasses both, because you can have good architecture and sloppy details.

2024-09-26 16:24 UTC, fantasai commented
[reverted to the original commit; please don't edit someone else's PR, it's very weird to have one's proposal unilaterally replaced with someone else's proposal]

2024-09-27 00:33 UTC, tantek commented
> [reverted to the original commit; please don't edit someone else's PR, it's very weird to have one's proposal unilaterally replaced with someone else's proposal]

Sorry this was me being clumsy with GitHub UI and attempting to suggest edits to a PR and clicking the wrong series of buttons / not understanding what I was doing. :/

2024-09-27 00:41 UTC, tantek requested changes
Suggest placing these additions at end of that list, both per cited examples, and perhaps more importantly following some of the priority of constituencies:
* users (a11y, i18n, s12y, privacy, security) 
* over implementers (technical soundness) 
* over theoretical purity (architectural integrity).

2024-09-27 00:41 UTC, tantek commented on Vision/Vision.bs
>  		and security.
```suggestion
		security, 
		technical soundness, 
		and architectural integrity.
```

2024-09-27 00:41 UTC, tantek commented on Vision/Vision.bs
> +		technical soundness,
```suggestion
```

2024-09-27 00:41 UTC, tantek commented on Vision/Vision.bs
> +		architectural integrity,
```suggestion
```

2024-09-27 17:21 UTC, fantasai commented
@tantek Done!

2024-09-27 17:58 UTC, tantek approved these changes

2024-09-27 18:06 UTC, cwilso approved these changes

2024-09-27 18:06 UTC, merged