Update Vision.bs
w3c/AB-public pull request #189
Opened 2024-10-01 20:06 UTC by celestaria

Add (WWW) in parenthesis's to line 49. All resources I found online state that the shorthand for the World Wide Web is WWW.

2024-10-02 20:32 UTC, tantek requested changes
Small markup improvement suggestion

2024-10-02 20:32 UTC, tantek commented on Vision/Vision.bs
> +	The World Wide Web (WWW) was originally conceived
```suggestion
	The World Wide Web (<abbr>WWW</abbr>) was originally conceived
```

2024-10-02 22:05 UTC, fantasai commented
We don't use the abbreviation WWW anywhere in this document, do we _need_ to introduce it here?

2024-10-03 04:30 UTC, tantek commented
> We don't use the abbreviation WWW anywhere in this document, do we _need_ to introduce it here? (What problem is it solving?)

I believe this may be an attempt to match the format of the opening of the next paragraph "The World Wide Web Consortium (W3C) " with the W3C in parentheses, and thus helps somewhat highlight to a casual reader that WWW and W3C are related (per common prose structure) but different (explicitly different looking abbrs).

2024-10-03 13:46 UTC, frivoal commented
Happy to defer to the editor's judgement on this one.

2024-10-04 20:04 UTC, cwilso commented
We *DO* use the term W3C in the document (around 30 times), so it makes sense to mark it.  We do NOT use the acronym WWW anywhere in the document, and it makes the very first sentence of the Introduction choppier to read.  I do not think this is a change we should take.

2024-10-04 20:08 UTC, tantek commented
> I do not think this is a change we should take.

Recognizing lack of consensus and the fact that this seems unnecessary before next publication, I suggest "defer" on this PR until after next Note publication.

2024-10-04 20:18 UTC, tantek commented
per chair+editor consensus on defer, labeling defer for reconsideration after next Note publication.

2025-02-26 00:05 UTC, tantek requested changes
Based on pushback in comments from @fantasai and @cwilso I have changed my mind and no longer think we need this in the Vision (certainly not for Statement).

Propose closing this PR without changes, without prejudice for any editorial or other improvements we might make in a future version of the Vision.

2025-03-06 16:03 UTC, cwilso commented
The AB concluded (based on the above) to close this.

2025-03-06 16:03 UTC, closed without merging