Update Vision.bs
w3c/AB-public pull request #190
Opened 2024-10-01 20:29 UTC by celestaria

Add ages (or age groups) and economic backgrounds (or economic status) to Vision.bs from https://github.com/w3c/AB-public/pull/185.

2024-10-02 20:30 UTC, tantek approved these changes
This improvement makes sense to me and reflects our (W3C) values

2024-10-02 22:07 UTC, fantasai requested changes
Seems fine to add, though given the focus we have on e.g. accessibility and internationalization, I would suggest shifting these down to put alongside "gender identities".

2024-10-03 05:37 UTC, chrisn commented on Vision/Vision.bs
>  		and inclusion of participants from different
```suggestion
		and inclusion of participants of different
```

I suggest rephrasing to "of different ages", as "from different ages" means something quite different.

2024-10-03 13:48 UTC, frivoal commented
I support this, especially with the comments from @fantasai and from @chrisn integrated.

2024-10-03 14:32 UTC, tantek approved these changes
While I agree with considering this addition, I don't think this is a blocker for publishing the next revision and would like to see it considered after.

2024-10-03 17:02 UTC, wareid commented
I think this is a worthwhile change, but I'd be ok to defer this to a future revision, and to align this with language in the code of conduct so we have consistency, does not need to happen today.

2024-10-04 20:07 UTC, cwilso reviewed
I do not think we need to expand this list further at this time.  I would recommend deferring this as an issue.

2024-10-04 20:11 UTC, tantek commented
based on editor+chair consensus on defer, labeling as such, for reconsideration after next Note publication.

2025-02-26 00:02 UTC, tantek requested changes
We no longer need this change because the Vision's Diversity point hyperlinks to the Code of Conduct for these and many more axes of diversity: https://w3c.github.io/AB-public/Vision#diversity. Propose closing without changes.

2025-03-06 16:03 UTC, cwilso commented
The AB concluded (based on the above) to close this.

2025-03-06 16:03 UTC, closed without merging