Re-organize, simplify, and de-duplicate
w3c/AB-public pull request #20
Opened 2022-08-25 22:28 UTC by dwsinger

This PR was my homework at the AB F2F to streamline the vision, giving it a better flow and structure, and remove duplication. I did not intend to change any content.

2022-08-25 22:33 UTC, tantek commented on Vision/README.md
> +Our vision is for a World Wide Web that is more inclusive, and more respectful of its users: a Web that supports truth better than falsehood, people more than profits, cooperation and communication r
I'd prefer to keep the previous wording, it has more punch. We can't shy away from the fact that the web has been used to amplify hate, hatred, hate crimes etc.

2022-08-25 22:35 UTC, tantek requested changes
This is a very good re-organization. Only thing I would change on this PR before merging is to keep the prior wording of "humanity rather than hate" (see specific inline comment on that.)

2022-08-25 22:35 UTC, dwsinger commented on Vision/README.md
> +Our vision is for a World Wide Web that is more inclusive, and more respectful of its users: a Web that supports truth better than falsehood, people more than profits, cooperation and communication r
OK.

2022-08-25 22:41 UTC, tantek approved these changes

2022-08-26 14:44 UTC, cwilso approved these changes

2022-09-01 15:06 UTC, merged