Semantic linefeeds added to document
w3c/AB-public pull request #43
Opened 2023-01-19 22:48 UTC by cwilso

This is a content-changeless commit - it only changes linefeeds that disappear in Markdown, so the Markdown file appears exactly the same, but should make future review easier.  (Confirmed with visual comparison and "git diff --word-diff --merge-base fd04e64".)

Fixes #42.

2023-01-19 22:49 UTC, cwilso commented
(Also, I'm on to you - this is just an attempt to break my habit of double-spaces after periods, which mess up semantic linefeeds.)

2023-01-19 23:06 UTC, tantek approved these changes
LGTM

2023-01-20 02:03 UTC, fantasai requested changes
Pretty good for a first shot! A couple of minor comments from my experience.

2023-01-20 02:03 UTC, fantasai commented on Vision/README.md
> +by ensuring security and privacy for users.
You need to indent this line (and all others that are continuations of a list item). Pick your indentation scheme; Tab and I of course prefer tabs ;) but you might want to go with the more conventional spaces indent.

2023-01-20 02:15 UTC, fantasai commented
Also don't forget to Squash merge when you're done!

2023-01-20 02:32 UTC, tantek approved these changes
Good catches @fantasai. Agreed with your suggested changes, especially the breaking of lists into one line per comma-delimited item. Reads much better for editing.

2023-01-20 21:18 UTC, cwilso commented on Vision/README.md
> +and considering public feedback.
I can't say that I disagree with you, but that's for a different day, under the guise of #23.

2023-01-20 21:30 UTC, merged